### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by vkorotkine** [CharlesCossette/pynav#13]
I think we need some integration tests for changes that we make.
Right now I just make sure to run a few of the previous examples to check nothing is broken. But running a single script will be easier when adding changes. My proposal is to run a test, and check the resulting time-avaraged NEES value to make sure it's "reasonable" even if its out of bounds.

**Comment by CharlesCossette** [comment]
One integration test that we could run is a purely noiseless filter run, and ensure that we have machine-precision zero errors throughout

**Comment by vkorotkine** [comment]
Addressed through PR #17
